version: "3"
services:
        web:
            build: .
            ports:
              - "3000:4000"
        mysql:
                image: mysql:5.7
                volumes:
                        - /Volumes/Cream/dockerImage/freerunServer/data:/var/lib/mysql     #挂载当前的data目录到容器默认mysql存储目录
                environment:                        #环境变量
                        - MYSQL_ROOT_PASSWORD=freeRun    #mysql的root密码
                        - MYSQL_DATABASE=WiatpZnTsWph5bMi     #mysql的初始化数据库
                ports:
                        - "3306:3306"   