#docker-compose build -t 9237074/freerun-mysql:v1 . 
version: "3"
services:
        mysql:
                image: mysql:5.7
                # restart: always
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - D:\cream\dockerImages\freerun-mysql/data:/var/lib/mysql
                        # - /Volumes/Cream/dockerImage/freerunServer/data:/var/lib/mysql     #挂载当前的data目录到容器默认mysql存储目录
                environment:                        #环境变量
                        - MYSQL_DATABASE=freeRun
                        # - MYSQL_USER=root
                        - MYSQL_ROOT_PASSWORD=123456
                ports:
                        - "3306:3306"   
        node:
                build: .
            #     restart: always
                ports:
                    - "4000:4000"